### ISSUE TITLE
Any way to reduce LaunchAtLoginHelper.app size?

### ISSUE THREAD

**Issue by deadcoder0904** [sindresorhus/LaunchAtLogin#16]
Currently it adds an additional overload of 11MB & I was checking out similar menubar apps which have much less size. 

Like f.lux is only 3.3MB & it has Launch At Login functionality. Is there any way to achieve this or do we need to go the difficult route & configure manually?

**Comment by sindresorhus** [comment]
You could write the helper app in Objective-C instead. The next macOS version will come with Swift built-in, since Swift will be ABI stable then, which means the helper app will then be only a few hundred kilobytes. Until then, I personally don't care. Disk space is cheap and 11 MB is not that much, especially since it's only temporary. And it's a lot less compressed.

**Comment by deadcoder0904** [comment]
Thanks, actually my app size was increased 11 MB more bcz I had my Scheme set to "Build" instead of "Release" 😂
