### ISSUE TITLE
Suggestion: Add ITSAppUsesNonExemptEncryption in helper's info.plist

### ISSUE THREAD

**Issue by xiao99xiao** [sindresorhus/LaunchAtLogin#55]
First, thanks for such a wonderful framework.

Currently the LaunchAtLoginHelper doesn't contain `ITSAppUsesNonExemptEncryption:No` in it's info.plist. Since App Store checks each info.plist in the uploaded app, unless every app's info.plist includes `ITSAppUsesNonExemptEncryption:No`, App Store Connect prompts the `App Uses Non-Exempt Encryption` confirmation every time when selecting a new build.

So maybe we could add it in the LaunchAtLoginHelper's info.plist?

**Comment by zackdotcomputer** [comment]
Hmm yeah I'd also appreciate this. I tried to do it [myself for a PR](https://github.com/zackdotcomputer/LaunchAtLogin/tree/add-encryption-plist) but it seems like there's no way to update the binary that's actually used in the final app unless you're @sindresorhus since it appears to be built, signed, and zipped beforehand rather than built-on-demand...

**Comment by sindresorhus** [comment]
I'll get to this soon.

**Comment by zackdotcomputer** [comment]
Thanks! The more I try to solve it the more I feel like the "I have no idea what I'm doing" dog. I definitely don't quite understand how you're making these .zip files, though I think I was definitely wrong an hour ago in my guess.
